Repository DomCR/ACadSharp, pull requests merged in 2022-12, with the labels that each got.

#77 Issue 63 slow dwg reader speed fix
  ACadSharp.Tests/IO/UserSamplesReader.cs
  ACadSharp/IO/DWG/DwgObjectSectionReader.cs
Labels: enhancement, good first issue

#74 Issue 63 Slow Read
  ACadSharp.Tests/IO/StressSamplesReader.cs
  ACadSharp/IO/DWG/DwgObjectSectionReader.cs
  ACadSharp/IO/DWG/DwgReader.cs
  ACadSharp/IO/Templates/DwgColorTemplate.cs
Labels: bug, enhancement

#84 Extends AutoCAD Testing Versions
  ACadSharp.Tests/IO/IOTestsBase.cs
Labels: enhancement

#82 MText refactoring
  ACadSharp/Entities/MText.cs
  ACadSharp/Entities/TextEntity.cs
  ACadSharp/IO/DWG/DwgObjectSectionReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  ACadSharp/IO/Templates/CadArcTemplate.cs
  ACadSharp/IO/Templates/CadInsertTemplate.cs
  ACadSharp/IO/Templates/CadTextEntityTemplate.cs
  ACadSharp/MathUtils.cs
Labels: bug, code refactoring

#87 Fix for TextVerticalAlignmentType
  ACadSharp/Entities/TextVerticalAlignmentType.cs
Labels: bug

#78 readers refactor
  ACadSharp/Classes/DxfClass.cs
  ACadSharp/Header/CadHeader.cs
  ACadSharp/IO/CadReaderBase.cs
  ACadSharp/IO/DWG/CRC.cs
  ACadSharp/IO/DWG/CRC32StreamHandler.cs
  ACadSharp/IO/DWG/CRC8StreamHandler.cs
  ACadSharp/IO/DWG/DwgHeaderReader.cs
  ACadSharp/IO/DWG/DwgLineWeightConverter.cs
  ACadSharp/IO/DWG/DwgReader.cs
  ACadSharp/IO/DWG/DwgReaderFlags.cs
  ACadSharp/IO/DWG/DwgSectionIO.cs
  ACadSharp/IO/DWG/DwgStreamReaders/Dwg2004LZ77.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgClassesReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgHandleReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectSectionReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC12.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs
  ACadSharp/IO/DWG/FileHeaders/DwgFileHeader15.cs
  ACadSharp/IO/DWG/FileHeaders/DwgSectionDefinition.cs
  ACadSharp/IO/DWG/FileHeaders/DwgSectionLocatorRecord.cs
  ACadSharp/IO/DXF/DxfReader.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfClassesSectionWriter.cs
  ACadSharp/IO/DXF/DxfWriter.cs
  ACadSharp/Tables/BlockRecord.cs
  ACadSharp/Types/DwgReferenceType.cs
Labels: code refactoring
