Repository DomCR/ACadSharp, pull requests merged in 2023-11, with the labels that each got.

#169 Implementation of MULTILEADER and MULTILEADERSTYLE
  ACadSharp.Tests/IO/MultiLeaderTests.cs
  ACadSharp/AttachmentType.cs
  ACadSharp/DxfFileToken.cs
  ACadSharp/DxfSubclassMarker.cs
  ACadSharp/Entities/MultiLeader.cs
  ACadSharp/FlowDirectionType.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
  ACadSharp/IO/Templates/CadInsertTemplate.cs
  ACadSharp/IO/Templates/CadMLeaderStyleTemplate.cs
  ACadSharp/IO/Templates/CadMLeaderTemplate.cs
  ACadSharp/LeaderContentType.cs
  ACadSharp/LeaderLinePropertOverrideFlags.cs
  ACadSharp/LineSpacingStyle.cs
  ACadSharp/MultiLeaderPathType.cs
  ACadSharp/MultiLeaderPropertyOverrideFlags.cs
  ACadSharp/Objects/MultiLeaderAnnotContext.cs
  ACadSharp/Objects/MultiLeaderAnnotContextClasses.cs
  ACadSharp/Tables/BlockContentConnectionType.cs
  ACadSharp/Tables/LeaderDrawOrderType.cs
  ACadSharp/Tables/MultiLeaderDrawOrderType.cs
  ACadSharp/Tables/MultiLeaderStyle.cs
  ACadSharp/TextAlignmentType.cs
  ACadSharp/TextAngleType.cs
  ACadSharp/TextAttachmentDirectionType.cs
  ACadSharp/TextAttachmentPoint.cs
  ACadSharp/TextAttachmentType.cs
  samples/multileader/sample_MLeader_AC1032.dwg
Labels: feature

#90 Dxf classes generation
  .gitignore
  ACadSharp/CadDocument.cs
  ACadSharp/Classes/DxfClass.cs
  ACadSharp/Classes/DxfClassCollection.cs
  ACadSharp/Classes/ProxyFlags.cs
  ACadSharp/IO/CadWriterBase.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgClassesReader.cs
  ACadSharp/IO/DWG/DwgWriter.cs
  ACadSharp/IO/DXF/DxfReader.cs
  ACadSharp/IO/DXF/DxfWriter.cs
  reference/ACadFileExploration.xlsx
Labels: feature

#201 Issue 198 index out of range in readmultileader
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/Objects/MultiLeaderAnnotContext.cs
Labels: bug

#199 ReadEnColor fix
  ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs
Labels: bug

#171 Dxf/Dwg writer MText
  ACadSharp.Tests/IO/DWG/DwgWriterSingleObjectTests.cs
  ACadSharp/Entities/MText.TextColumn.cs
  ACadSharp/Entities/MText.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
  ACadSharp/Tables/Layer.cs
Labels: enhancement

#204 Replace double[] with Matrix4
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/Objects/MultiLeaderAnnotContext.cs
Labels: enhancement

#203 Text rotation fix
  ACadSharp/Entities/TextEntity.cs
Labels: bug
