Repository DomCR/ACadSharp, pull requests merged in 2024-03, with the labels that each got.

#296 20240304 mme dimension style comment
  ACadSharp/Tables/DimensionStyle.cs
Labels: documentation

#306 Multileader DwgReader jump fix
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
Labels: bug

#307 MultiLeader dwg reader pre2010
  ACadSharp.Tests/IO/MultiLeaderTests.cs
  ACadSharp/Entities/MultiLeader.cs
  ACadSharp/IO/DWG/DwgSectionIO.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  samples/multileader/sample_MLeader_AC1015.dwg
  samples/multileader/sample_MLeader_AC1018.dwg
  samples/multileader/sample_MLeader_AC1021.dwg
  samples/multileader/sample_MLeader_AC1024.dwg
  samples/multileader/sample_MLeader_AC1027.dwg
Labels: enhancement

#311 DwgWriter unlisted objects
  ACadSharp/Classes/DxfClassCollection.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Common.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC24.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgmMergedStreamWriter.cs
  ACadSharp/IO/DWG/DwgStreamWriters/IDwgStreamWriter.cs
  ACadSharp/Objects/CadDictionary.cs
Labels: enhancement

#309 Cad document collections
  ACadSharp.Tests/Objects/Collections/ScaleCollectionTests.cs
  ACadSharp/CadDocument.cs
  ACadSharp/IO/CadDocumentBuilder.cs
  ACadSharp/IO/Templates/CadDictionaryTemplate.cs
  ACadSharp/LayoutCollection.cs
  ACadSharp/Objects/CadDictionary.cs
  ACadSharp/Objects/Collections/GroupCollection.cs
  ACadSharp/Objects/Collections/LayoutCollection.cs
  ACadSharp/Objects/Collections/MLeaderStyleCollection.cs
  ACadSharp/Objects/Collections/MLineStyleCollection.cs
  ACadSharp/Objects/Collections/ObjectDictionaryCollection.cs
  ACadSharp/Objects/Collections/ScaleCollection.cs
  ACadSharp/Objects/Group.cs
  ACadSharp/Objects/IDictionaryEntry.cs
  ACadSharp/Objects/Layout.cs
  ACadSharp/Objects/MLineStyle.cs
  ACadSharp/Objects/MultiLeaderStyle.cs
  ACadSharp/Objects/Scale.cs
Labels: enhancement

#322 Dxf writer fix color writer
  ACadSharp.Tests/IO/WriterSingleObjectTests.cs
  ACadSharp/Color.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfReaderBase.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfHeaderSectionWriter.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs
  ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs
  ACadSharp/Tables/TableEntry.cs
  ACadSharp/Tables/TextStyle.cs
Labels: bug

#324 rollback
  ACadSharp/CadDocument.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgHeaderWriter.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgMergedStreamWriter.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgmMergedStreamWriterAC14.cs
  ACadSharp/IO/DWG/DwgStreamWriters/IDwgStreamWriter.cs
  ACadSharp/IO/Templates/CadDictionaryTemplate.cs
  ACadSharp/Objects/Collections/ObjectDictionaryCollection.cs
Labels: bug

#326 VPorts allow duplicated names
  ACadSharp.Tests/Common/DocumentIntegrity.cs
  ACadSharp/CadObject.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/Tables/Collections/Table.cs
  ACadSharp/Tables/Collections/VPortsTable.cs
Labels: bug

#328 Issue 321 textstyle isshape flag
  .editorconfig
  ACadSharp.Tests/IO/IOTests.cs
  ACadSharp.Tests/Tables/Collections/BlockRecordTests.cs
  ACadSharp.Tests/Tables/Collections/TextStylesTableTests.cs
  ACadSharp.Tests/Tables/TableEntryTests.cs
  ACadSharp/Attributes/DxfCodeValueAttribute.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfTablesSectionWriter.cs
  ACadSharp/Tables/Collections/AppIdsTable.cs
  ACadSharp/Tables/Collections/BlockRecordsTable.cs
  ACadSharp/Tables/Collections/DimensionStylesTable.cs
  ACadSharp/Tables/Collections/LayersTable.cs
  ACadSharp/Tables/Collections/LineTypesTable.cs
  ACadSharp/Tables/Collections/Table.cs
  ACadSharp/Tables/Collections/TextStylesTable.cs
  ACadSharp/Tables/Collections/UCSTable.cs
  ACadSharp/Tables/Collections/VPortsTable.cs
  ACadSharp/Tables/Collections/ViewsTable.cs
  ACadSharp/Tables/TableEntry.cs
  ACadSharp/Tables/TextStyle.cs
Labels: bug

#329 Issue 327 true color r and b interchanged
  ACadSharp.Tests/IO/ColorTests.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderAC18.cs
  samples/color_samples/color_sample.dwg
Labels: bug

#333 Issue 327 true color r and b interchanged
  ACadSharp.Tests/IO/ColorTests.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterAC18.cs
  ACadSharp/IO/DWG/DwgStreamWriters/DwgStreamWriterBase.cs
  samples/color_samples/color_sample_AC1018.dwg
Labels: bug
