Repository DomCR/ACadSharp, pull requests merged in 2024-10, with the labels that each got.

#463 Arc PolygonalVertexes fix
  src/ACadSharp/Entities/Arc.cs
Labels: bug

#464 Viewport refactor
  src/ACadSharp/Entities/Viewport.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
  src/ACadSharp/Tables/Layer.cs
Labels: code refactoring

#469 Issue 458 hatch clone fix
  src/ACadSharp.Tests/IO/LocalSampleTests.cs
  src/ACadSharp/Entities/Hatch.cs
  src/ACadSharp/Entities/HatchPattern.cs
Labels: bug

#468 Link to Shared Project
  README.md
Labels: documentation

#481 Viewport scale factor
  src/ACadSharp/CadDocument.cs
  src/ACadSharp/Entities/Viewport.cs
  src/ACadSharp/Objects/PlotSettings.cs
  src/ACadSharp/Objects/Scale.cs
  src/ACadSharp/Tables/BlockRecord.cs
  src/ACadSharp/Types/LineWeightType.cs
Labels: enhancement
