Repository DomCR/ACadSharp, pull requests merged in 2024-06, with the labels that each got.

#355 fixed xrecord data reading
  ACadSharp/DxfCode.cs
  ACadSharp/GroupCodeValue.cs
  ACadSharp/GroupCodeValueType.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgMergedReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgStreamReaderBase.cs
  ACadSharp/IO/DWG/DwgStreamReaders/IDwgStreamReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfReaderBase.cs
  ACadSharp/IO/DXF/DxfStreamWriter/DxfBinaryWriter.cs
Labels: bug

#356 Create default elements fix
  ACadSharp.Tests/IO/LocalSampleTests.cs
  ACadSharp/CadDocument.cs
  ACadSharp/Entities/CadImageBase.cs
  ACadSharp/IO/CadDocumentBuilder.cs
  ACadSharp/IO/DWG/DwgDocumentBuilder.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DXF/DxfDocumentBuilder.cs
Labels: enhancement

#360 Increase reading performance
  ACadSharp.Examples/Common/NotificationHelper.cs
  ACadSharp.Examples/Program.cs
  ACadSharp.Tests/IO/LocalSampleTests.cs
  ACadSharp.Tests/Internal/DwgObjectWriterTests.cs
  ACadSharp/IO/CadDocumentBuilder.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DXF/DxfDocumentBuilder.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  ACadSharp/IO/Templates/CadHatchTemplate.CadBoundaryPathTemplate.cs
  ACadSharp/IO/Templates/CadLineTypeTemplate.cs
  ACadSharp/IO/Templates/CadMLineStyleTemplate.cs
  ACadSharp/IO/Templates/DwgGroupTemplate.cs
  ACadSharp/IO/Templates/ICadObjectTemplate.cs
Labels: bug, enhancement

#362 Separate the dictionary key from the entry name
  ACadSharp.Tests/IO/LocalSampleTests.cs
  ACadSharp/IO/Templates/CadDictionaryTemplate.cs
  ACadSharp/Objects/CadDictionary.cs
Labels: bug

#364 Irregular dxf no version
  ACadSharp.Tests/IO/DWG/DwgWriterTests.cs
  ACadSharp.Tests/Internal/DwgObjectWriterTests.cs
  ACadSharp/Exceptions/CadNotSupportedException.cs
  ACadSharp/Exceptions/DwgNotSupportedException.cs
  ACadSharp/IO/CadDocumentBuilder.cs
  ACadSharp/IO/DWG/DwgDocumentBuilder.cs
  ACadSharp/IO/DWG/DwgReader.cs
  ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  ACadSharp/IO/DWG/DwgWriter.cs
  ACadSharp/IO/DWG/FileHeaders/DwgFileHeader.cs
  ACadSharp/IO/DXF/DxfDocumentBuilder.cs
  ACadSharp/IO/DXF/DxfReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfBinaryReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfEntitiesSectionReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfObjectsSectionReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfStreamReaderBase.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfTablesSectionReader.cs
  ACadSharp/IO/DXF/DxfStreamReader/DxfTextReader.cs
  ACadSharp/IO/Templates/CadEntityTemplate.cs
  ACadSharp/IO/Templates/CadMLineStyleTemplate.cs
  ACadSharp/IO/Templates/CadPolyLineTemplate.cs
  ACadSharp/IO/Templates/CadShapeTemplate.cs
  ACadSharp/IO/Templates/CadTableEntryTemplate.cs
  ACadSharp/IO/Templates/CadVPortTemplate.cs
  ACadSharp/IO/Templates/CadVertexTemplate.cs
  ACadSharp/IO/Templates/CadViewportTemplate.cs
  ACadSharp/IO/Templates/DwgTextEntityTemplate.cs
  ACadSharp/IO/Templates/ICadTableEntryTemplate.cs
  ACadSharp/IO/Templates/ICadTableTemplate.cs
  ACadSharp/Tables/TableEntry.cs
  ACadSharp/Tables/TextStyle.cs
Labels: enhancement

#373 Cad object collection clone fix
  ACadSharp.Tests/Common/CadObjectTestUtils.cs
  ACadSharp.Tests/Entities/InsertTest.cs
  ACadSharp.Tests/Entities/PolylineTest.cs
  ACadSharp.Tests/Tables/BlockRecordTests.cs
  ACadSharp/Entities/Insert.cs
  ACadSharp/Entities/PolyFaceMesh.cs
  ACadSharp/Entities/PolyLine.cs
  ACadSharp/Entities/PolyfaceMesh.cs
  ACadSharp/Tables/BlockRecord.cs
Labels: bug
