Repository DomCR/ACadSharp, pull requests merged in 2025-04, with the labels that each got.

#600 Issue 598
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/IO/DWG/DwgReader.cs
  src/ACadSharp/IO/DWG/DwgReaderConfiguration.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgSummaryInfoReader.cs
Labels: bug, minor

#525 Issue-524 Explode Hatch
  src/ACadSharp.Tests/Entities/HatchTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Entities/Hatch.BoundaryPath.Arc.cs
  src/ACadSharp/Entities/Hatch.BoundaryPath.Edge.cs
  src/ACadSharp/Entities/Hatch.BoundaryPath.Ellipse.cs
  src/ACadSharp/Entities/Hatch.BoundaryPath.Line.cs
  src/ACadSharp/Entities/Hatch.BoundaryPath.Polyline.cs
  src/ACadSharp/Entities/Hatch.BoundaryPath.Spline.cs
  src/ACadSharp/Entities/Hatch.cs
  src/ACadSharp/Entities/Line.cs
  src/ACadSharp/Entities/PolyLine.cs
  src/ACadSharp/Entities/PolyLine2D.cs
  src/ACadSharp/Entities/PolyLine3D.cs
  src/ACadSharp/Entities/PolyfaceMesh.cs
  src/ACadSharp/Entities/Spline.cs
  src/ACadSharp/Entities/Vertex.cs
  src/ACadSharp/Entities/Vertex2D.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
  src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
  src/ACadSharp/IO/Templates/CadPolyLineTemplate.cs
Labels: enhancement, minor

#602 add lines example file
  src/ACadSharp.Examples/Entities/LineExample.cs
Labels: documentation

#606 Issue 605 cad document performance fix
  src/ACadSharp.Tests/CadDocumentTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/CadDocument.cs
Labels: enhancement, minor

#610 addCadObject fix
  src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/CadDocument.cs
  src/ACadSharp/Header/CadHeader.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgHeaderReader.cs
Labels: bug, minor

#614 Issue 612 dxf to dwg
  src/ACadSharp.Tests/IO/IOTests.cs
  src/ACadSharp.Tests/IO/LocalSampleTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/CadDocument.cs
  src/ACadSharp/Classes/DxfClassCollection.cs
  src/ACadSharp/IO/CadWriterBase.cs
  src/ACadSharp/IO/CadWriterConfiguration.cs
  src/ACadSharp/IO/DXF/DxfReader.cs
  src/ACadSharp/IO/Templates/CadBlockRecordTemplate.cs
  src/ACadSharp/Objects/CadDictionary.cs
Labels: bug, minor

#604 add circle hatch example file
  src/ACadSharp.Examples/Entities/CircleHatchExample.cs
Labels: documentation

#635 Version
  src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
  src/ACadSharp/ACadSharp.csproj
Labels: minor

#636 MText defaults fix
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Entities/MText.cs
Labels: bug, minor

#638 HasHookline as read only
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Entities/HookLineDirection.cs
  src/ACadSharp/Entities/Leader.cs
  src/ACadSharp/Entities/LeaderPathType.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Entities.cs
  src/ACadSharp/IO/DXF/DxfStreamReader/DxfSectionReaderBase.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
Labels: minor

#621 20250402 nka multileader clone bugfix
  src/ACadSharp.Tests/IO/MultiLeaderTests.cs
  src/ACadSharp/Classes/DxfClassCollection.cs
  src/ACadSharp/Entities/HatchPattern.cs
  src/ACadSharp/Entities/MultiLeader.BlockAttribute.cs
  src/ACadSharp/Entities/MultiLeader.cs
  src/ACadSharp/FlowDirectionType.cs
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
  src/ACadSharp/Objects/MultiLeaderAnnotContext.cs
  src/ACadSharp/Objects/MultiLeaderAnnotContextClasses.cs
  src/ACadSharp/Objects/MultiLeaderStyle.cs
Labels: bug, enhancement, minor

#586 issue-480_spline-polygonalvertices
  src/ACadSharp/Entities/Spline.cs
Labels: feature

#647 issue-622 WriteOptional flag dxf
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfSectionWriterBase.Entities.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfStreamWriterBase.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/IDxfStreamWriter.cs
  src/ACadSharp/IO/DXF/DxfWriter.cs
  src/ACadSharp/IO/DXF/DxfWriterConfiguration.cs
Labels: bug, minor

#646 Escape special characters when writing strings to svg
  src/ACadSharp/IO/SVG/SvgXmlWriter.cs
Labels: bug

#644 Issue 480 spline polygonalvertices transfer
  src/ACadSharp.Tests/Entities/AttributeDefinitionTests.cs
  src/ACadSharp.Tests/Entities/CommonEntityTests.cs
  src/ACadSharp.Tests/Entities/EntityTests.cs
  src/ACadSharp.Tests/Entities/SplineTests.cs
  src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Entities/PolyLine3D.cs
  src/ACadSharp/Entities/Spline.cs
Labels: feature, minor

#650 clone remove events
  src/ACadSharp.Tests/CadObjectTests.cs
  src/ACadSharp.Tests/Objects/NonGraphicalObjectTests.cs
  src/ACadSharp.Tests/Tables/TableEntryTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Extensions/CadObjectExtensions.cs
  src/ACadSharp/Objects/CadDictionary.cs
  src/ACadSharp/Objects/NonGraphicalObject.cs
  src/ACadSharp/Tables/Collections/Table.cs
  src/ACadSharp/Tables/TableEntry.cs
Labels: bug, minor
