Repository DomCR/ACadSharp, pull requests merged in 2025-07, with the labels that each got.

#700 issue-696 sortentities fix
  src/ACadSharp.Tests/Objects/SortEntitiesTableTests.cs
  src/ACadSharp.Tests/Tables/BlockRecordTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
  src/ACadSharp/IO/Templates/CadSortensTableTemplate.cs
  src/ACadSharp/Objects/SortEntitiesTable.Sorter.cs
  src/ACadSharp/Objects/SortEntitiesTable.cs
  src/ACadSharp/Tables/BlockRecord.cs
Labels: bug, SPIKE, major

#701 20250703 13 666 spline transform fails
  src/ACadSharp/Entities/Spline.cs
Labels: bug

#717 Issue 716
  src/ACadSharp.Tests/IO/WriterSingleObjectTests.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/IO/DWG/DwgStreamReaders/DwgObjectReader.cs
  src/ACadSharp/IO/DWG/DwgStreamWriters/DwgObjectWriter.Objects.cs
  src/ACadSharp/IO/DXF/DxfStreamWriter/DxfObjectsSectionWriter.cs
  src/ACadSharp/Objects/BookColor.cs
  src/ACadSharp/Objects/NonGraphicalObject.cs
Labels: bug, minor

#718 SVG tests
  samples/svg/export_sample.dwg
  src/ACadSharp.Tests/IO/IOTestsBase.cs
  src/ACadSharp.Tests/IO/SVG/SvgWriterTests.cs
  src/ACadSharp.Tests/TestModels/FileModel.cs
  src/ACadSharp/Color.cs
  src/ACadSharp/Entities/Entity.cs
  src/ACadSharp/Entities/IText.cs
  src/ACadSharp/Entities/LwPolyline.Vertex.cs
  src/ACadSharp/Entities/MText.cs
  src/ACadSharp/Entities/TextEntity.cs
  src/ACadSharp/IO/SVG/SvgConfiguration.cs
  src/ACadSharp/IO/SVG/SvgConverter.cs
  src/ACadSharp/IO/SVG/SvgXmlWriter.cs
  src/ACadSharp/IO/SvgWriter.cs
Labels: enhancement, code refactoring

#721 SVG paper units
  src/ACadSharp.Tests/IO/IOTestsBase.cs
  src/ACadSharp/ACadSharp.csproj
  src/ACadSharp/Extensions/UnitExtensions.cs
  src/ACadSharp/IO/SVG/SvgConfiguration.cs
  src/ACadSharp/IO/SVG/SvgConverter.cs
  src/ACadSharp/IO/SVG/SvgXmlWriter.cs
  src/ACadSharp/Objects/PaperMargin.cs
  src/ACadSharp/Objects/PlotPaperUnits.cs
  src/ACadSharp/Objects/PlotSettings.cs
Labels: enhancement, code refactoring, minor
